### ISSUE TITLE
我无法正常使用插件，是否是我的使用方式不对，或者插件有结构bug？

### ISSUE THREAD

**Issue by NuclearSnack** [gongjinzhou/quickInput-for-uTools#1]
具体来说，首先我每次打开都会有弹窗，很烦（不过是小问题）
![image](https://github.com/user-attachments/assets/11be4a93-b966-42e2-b9f5-c2d5cca99474)

然后我之前加号设置的快捷语都会不见：
![image](https://github.com/user-attachments/assets/581ab6bd-4611-497f-a37f-9f99786d58ab)

而功能窗里是有这些的，不过全都有两份，疑似是一份复制一份输入
![image](https://github.com/user-attachments/assets/b21e6da2-2a9a-4f70-8d6a-e7ff07d4f419)

再然后我用主输入框输入我的输入码，也确实会有相应的按钮，但是点击它不会发生输入和复制，只会进入插件主页面
![image](https://github.com/user-attachments/assets/5198e329-50c3-44b3-a1cc-ac2c7c8d8011)
(单击第一个按钮后：)
![image](https://github.com/user-attachments/assets/782fdbba-877c-49da-afa7-1dc890b369fc)

所以现在插件在我手中是完全没办法工作的。我很喜欢这个功能，请修复或教学，谢谢

**Comment by gongjinzhou** [comment]
抱歉我才看到你的信息，我没有复现你的问题，根据你git上反馈的信息，看起来应该是在获取数据库信息时出现了错误，但是具体的原因由于我无法复现暂时不太清楚，你可以尝试卸载插件重新安装一下，如果还是不行可以在git上提交你的使用平台和具体复现步骤，谢谢
